# Site Variables
name:             "Elokrainz"
description:      "Null."
url:              "http://elokrainz.github.io"
blog:             "/blog"
blog_categories:  "/blog/categories"
blog_tags:        "/blog/tags"
blog_rss:         "/blog/feed.xml"

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Blog Permalinks
permalink:        "/blog/:categories/:title/"

# Blog Pagination
paginate:         5
paginate_path:    "/blog/page:num"

# Server Info
exclude:          [".gitignore", "less", "CNAME", "LICENSE", "README.md"]
port:             4001